version: 0.2

env:
  parameter-store:
    - AWS_ACCESS_KEY_ID: MavenReadWriteKeyId
    - AWS_SECRET_ACCESS_KEY: MavenReadWriteKeySecret

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn deploy
#      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
#artifacts:
#  files:
#    - target/codebuild-test-1.0.jar
reports:
  report-group1: #surefire junit reports
    files:
      - '**/*'
    base-directory: 'target/surefire-reports'